// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sell_movie.Entities;

#nullable disable

namespace sell_movie.Migrations
{
    [DbContext(typeof(web_cinema3Context))]
    [Migration("20231224101913_AddTongTienThanhToanColumnToThanhToan")]
    partial class AddTongTienThanhToanColumnToThanhToan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("sell_movie.Entities.Ctdatve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GiaVe")
                        .HasColumnType("int");

                    b.Property<int>("MaDatVe")
                        .HasColumnType("int");

                    b.Property<string>("MaGhe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaDatVe");

                    b.HasIndex("MaGhe");

                    b.ToTable("ctdatve", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Ghe", b =>
                {
                    b.Property<string>("MaGhe")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("maGhe");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaGhe")
                        .HasName("PK__ghe__2D87404C107725C4");

                    b.HasIndex("MaPhong");

                    b.ToTable("ghe", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Giave", b =>
                {
                    b.Property<string>("MaGiaVe")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GiaVe1")
                        .HasColumnType("int")
                        .HasColumnName("GiaVe");

                    b.Property<string>("TenLoaiVe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaGiaVe")
                        .HasName("PK__giave__5A25399ABC716995");

                    b.ToTable("giave", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Khachhang", b =>
                {
                    b.Property<string>("Makhachhang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("makhachhang");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("diachi");

                    b.Property<bool>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenkhachhang");

                    b.HasKey("Makhachhang")
                        .HasName("PK__khachhan__52F5E8385A6956C6");

                    b.ToTable("khachhang", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Lichchieu", b =>
                {
                    b.Property<string>("MaLichChieu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<TimeSpan>("GioChieu")
                        .HasColumnType("time");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("date");

                    b.HasKey("MaLichChieu")
                        .HasName("PK__lichchie__DC740197AC81BFE7");

                    b.ToTable("lichchieu", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Lichchieuphim", b =>
                {
                    b.Property<string>("MaLichPhim")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaLichChieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaLichPhim")
                        .HasName("PK__lichchie__775BC2F5F00D7847");

                    b.HasIndex("MaLichChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("lichchieuphim", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Nguoidung", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<bool>("Role")
                        .HasColumnType("bit")
                        .HasColumnName("role");

                    b.HasKey("Username")
                        .HasName("PK__nguoidun__F3DBC5731E6A02BE");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("nguoidung", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Nhanvien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Gioitinh")
                        .HasColumnType("tinyint")
                        .HasColumnName("gioitinh");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__nhanvien__77B2CA47CF222EDA");

                    b.ToTable("nhanvien", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Phim", b =>
                {
                    b.Property<string>("MaPhim")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("banner");

                    b.Property<string>("MaQuocGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaTl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MaTL");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Ngaykhoichieu")
                        .HasColumnType("date")
                        .HasColumnName("ngaykhoichieu");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Thoiluong")
                        .HasColumnType("int")
                        .HasColumnName("thoiluong");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaPhim")
                        .HasName("PK__phim__4AC03DE30B09D95B");

                    b.HasIndex("MaQuocGia");

                    b.HasIndex("MaTl");

                    b.ToTable("phim", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoChoNgoi")
                        .HasColumnType("int");

                    b.Property<int>("SoHang")
                        .HasColumnType("int");

                    b.Property<int>("Socot")
                        .HasColumnType("int")
                        .HasColumnName("socot");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaPhong")
                        .HasName("PK__phong__20BD5E5B9A5DDFEE");

                    b.ToTable("phong", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Quocgium", b =>
                {
                    b.Property<string>("MaQuocgia")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenQuocGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaQuocgia")
                        .HasName("PK__quocgia__2B98FAF9CC4A5084");

                    b.ToTable("quocgia", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Tdkhachhang", b =>
                {
                    b.Property<string>("Makhachhang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("makhachhang");

                    b.Property<int?>("Diemkhachhang")
                        .HasColumnType("int");

                    b.Property<string>("HangKh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HangKH");

                    b.HasKey("Makhachhang");

                    b.ToTable("tdkhachhang", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Thanhtoan", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaDatVe")
                        .HasColumnType("int");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("Phuongthucthanhtoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phuongthucthanhtoan");

                    b.Property<int>("TongTienThanhToan")
                        .HasColumnType("int");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__thanhtoa__D4B2584496E304E5");

                    b.HasIndex("MaDatVe");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("thanhtoan", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Theloai", b =>
                {
                    b.Property<string>("MaTl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MaTL");

                    b.Property<string>("TenTl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenTL");

                    b.HasKey("MaTl")
                        .HasName("PK__theloai__272500710E2EA98D");

                    b.ToTable("theloai", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Trangthaighe", b =>
                {
                    b.Property<string>("Maghe")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaLichChieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Maghe");

                    b.HasIndex("MaLichChieu");

                    b.HasIndex("MaPhong");

                    b.ToTable("trangthaighe", (string)null);
                });

            modelBuilder.Entity("sell_movie.Entities.Ttdatve", b =>
                {
                    b.Property<int>("MaDatVe")
                        .HasColumnType("int");

                    b.Property<string>("MaLichPhim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("date");

                    b.HasKey("MaDatVe")
                        .HasName("PK__ttdatve__6A32C59304FC1FD9");

                    b.HasIndex("MaLichPhim");

                    b.ToTable("ttdatve", (string)null);
                });

            modelBuilder.Entity("sell_movie.Secure.Data.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoidungUsername")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("nguoidungUsername");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("sell_movie.Entities.Ctdatve", b =>
                {
                    b.HasOne("sell_movie.Entities.Ttdatve", "ttdatveNavigation")
                        .WithMany()
                        .HasForeignKey("MaDatVe")
                        .IsRequired()
                        .HasConstraintName("FK__ctdatve__MaDatVe__5812160A");

                    b.HasOne("sell_movie.Entities.Ghe", "MaGheNavigation")
                        .WithMany("Ctdatves")
                        .HasForeignKey("MaGhe")
                        .IsRequired()
                        .HasConstraintName("FK__ctdatve__MaGhe__5812160E");

                    b.Navigation("MaGheNavigation");

                    b.Navigation("ttdatveNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Ghe", b =>
                {
                    b.HasOne("sell_movie.Entities.Phong", "MaPhongNavigation")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK__ghe__MaPhong__5535A963");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Lichchieuphim", b =>
                {
                    b.HasOne("sell_movie.Entities.Lichchieu", "MaLichChieuNavigation")
                        .WithMany("Lichchieuphims")
                        .HasForeignKey("MaLichChieu")
                        .IsRequired()
                        .HasConstraintName("FK__lichchieu__MaLic__628FA481");

                    b.HasOne("sell_movie.Entities.Phim", "MaPhimNavigation")
                        .WithMany("Lichchieuphims")
                        .HasForeignKey("MaPhim")
                        .IsRequired()
                        .HasConstraintName("FK__lichchieu__MaPhi__6477ECF3");

                    b.HasOne("sell_movie.Entities.Phong", "MaPhongNavigation")
                        .WithMany("Lichchieuphims")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK__lichchieu__MaPho__6383C8BA");

                    b.Navigation("MaLichChieuNavigation");

                    b.Navigation("MaPhimNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Nguoidung", b =>
                {
                    b.HasOne("sell_movie.Entities.Nhanvien", "MaNhanVienNavigation")
                        .WithMany("Nguoidungs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__nguoidung__MaNha__6754599E");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Phim", b =>
                {
                    b.HasOne("sell_movie.Entities.Quocgium", "MaQuocGiaNavigation")
                        .WithMany("Phims")
                        .HasForeignKey("MaQuocGia")
                        .IsRequired()
                        .HasConstraintName("FK__phim__MaQuocGia__5070F446");

                    b.HasOne("sell_movie.Entities.Theloai", "MaTlNavigation")
                        .WithMany("Phims")
                        .HasForeignKey("MaTl")
                        .IsRequired()
                        .HasConstraintName("FK__phim__MaTL__4F7CD00D");

                    b.Navigation("MaQuocGiaNavigation");

                    b.Navigation("MaTlNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Tdkhachhang", b =>
                {
                    b.HasOne("sell_movie.Entities.Khachhang", "MakhachhangNavigation")
                        .WithMany()
                        .HasForeignKey("Makhachhang")
                        .IsRequired()
                        .HasConstraintName("FK__tdkhachha__makha__5DCAEF64");

                    b.Navigation("MakhachhangNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Thanhtoan", b =>
                {
                    b.HasOne("sell_movie.Entities.Ttdatve", "MaDatVeNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("MaDatVe")
                        .IsRequired()
                        .HasConstraintName("FK__thanhtoan__MaDat__6A30C649");

                    b.HasOne("sell_movie.Entities.Nhanvien", "MaNhanVienNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__thanhtoan__MaNha__6B24EA82");

                    b.Navigation("MaDatVeNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Trangthaighe", b =>
                {
                    b.HasOne("sell_movie.Entities.Lichchieu", "MaLichChieuNavigation")
                        .WithMany()
                        .HasForeignKey("MaLichChieu")
                        .IsRequired()
                        .HasConstraintName("FK__trangthai__MaLic__6EF57B66");

                    b.HasOne("sell_movie.Entities.Phong", "MaPhongNavigation")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK__trangthai__MaPho__6E01572D");

                    b.HasOne("sell_movie.Entities.Ghe", "MagheNavigation")
                        .WithMany()
                        .HasForeignKey("Maghe")
                        .IsRequired()
                        .HasConstraintName("FK__trangthai__Maghe__6D0D32F4");

                    b.Navigation("MaLichChieuNavigation");

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MagheNavigation");
                });

            modelBuilder.Entity("sell_movie.Entities.Ttdatve", b =>
                {
                    b.HasOne("sell_movie.Entities.Lichchieuphim", "MaLichPhimNavigation")
                        .WithMany("Ttdatves")
                        .HasForeignKey("MaLichPhim")
                        .IsRequired()
                        .HasConstraintName("FK__ttdatve__MaLichP__71D1E811");

                    b.Navigation("MaLichPhimNavigation");
                });

            modelBuilder.Entity("sell_movie.Secure.Data.RefreshToken", b =>
                {
                    b.HasOne("sell_movie.Entities.Nguoidung", "nguoidung")
                        .WithMany()
                        .HasForeignKey("nguoidungUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoidung");
                });

            modelBuilder.Entity("sell_movie.Entities.Ghe", b =>
                {
                    b.Navigation("Ctdatves");
                });

            modelBuilder.Entity("sell_movie.Entities.Lichchieu", b =>
                {
                    b.Navigation("Lichchieuphims");
                });

            modelBuilder.Entity("sell_movie.Entities.Lichchieuphim", b =>
                {
                    b.Navigation("Ttdatves");
                });

            modelBuilder.Entity("sell_movie.Entities.Nhanvien", b =>
                {
                    b.Navigation("Nguoidungs");

                    b.Navigation("Thanhtoans");
                });

            modelBuilder.Entity("sell_movie.Entities.Phim", b =>
                {
                    b.Navigation("Lichchieuphims");
                });

            modelBuilder.Entity("sell_movie.Entities.Phong", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("Lichchieuphims");
                });

            modelBuilder.Entity("sell_movie.Entities.Quocgium", b =>
                {
                    b.Navigation("Phims");
                });

            modelBuilder.Entity("sell_movie.Entities.Theloai", b =>
                {
                    b.Navigation("Phims");
                });

            modelBuilder.Entity("sell_movie.Entities.Ttdatve", b =>
                {
                    b.Navigation("Thanhtoans");
                });
#pragma warning restore 612, 618
        }
    }
}
